[versions]
loom = "1.6-SNAPSHOT"
architecturyPlugin = "3.4-SNAPSHOT"
shadow = "8.1.1"
minecraft = "1.21"
architecturyApi = "13.0.2"
yarnNeoforge = "1.21+build.4"
yarnFabric = "1.21+build.1:v2"
fabricLoader = "0.16.5"
fabricApi = "0.102.0+1.21"
fabricKotlin = "1.12.1+kotlin.2.0.20"
neoforge = "21.0.42-beta"
kotlinforforge = "5.5.0"
kotlin = "2.0.20"

[libraries]
minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }
yarnNeoforge = { module = "dev.architectury:yarn-mappings-patch-neoforge", version.ref = "yarnNeoforge" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricKotlin" }
architectury-fabric = { module = "dev.architectury:architectury-fabric", version.ref = "architecturyApi" }
architectury-neoforge = { module = "dev.architectury:architectury-neoforge", version.ref = "architecturyApi" }
architectury = { module = "dev.architectury:architectury", version.ref = "architecturyApi" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
kotlinforforge = { module = "thedarkcolour:kotlinforforge-neoforge", version.ref = "kotlinforforge" }

[plugins]
loom = { id = "dev.architectury.loom", version.ref = "loom" }
architectury = { id = "architectury-plugin", version.ref = "architecturyPlugin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]